### ISSUE TITLE
Planjamento do roadmap

### ISSUE THREAD

**Issue by Diego-Brocanelli** [training-center/java-study-group#10]
Olá, amigos.

Gostaria de auxiliar na construção do roadmap da comunidade, para que assim possamos agregar mais participantes e auxilia-los nos estudos.

## Minhas sugestão : 

- **Níveis**
    - Iniciante
    - Intermediário
    - Avançado

## Para cada nível podemos definir os seguintes pontos, sendo:
- Indicação de materiais de estudos.
- Indicação de caminhos a seguir.
- Possíveis pessoas a serem contatadas para auxílio.
- Projetos práticos, para que o membro possa por em prática o que o roadmap propõem. 

## Alguns pontos importantes que devemos trabalhar na comunidade, sendo:

1. O interesse pelo estudo é individual, sendo assim ninguém é obrigado a construir estruturas para que outras pessoas apenas consumam.
2. Somo uma COMUNIDADE e como tal, todos tem papel fundamental no crescimento e manutenção do mesmo, onde o trabalho voluntário e conjunto faz com que adquirimos mais conhecimento e possamos auxiliar outras pessoas a atingirem seus objetivos.
3. Todos no grupo tem a mesma importância, independente do nível de conhecimento e tempo de carreira.
4. Sem pessoas não há comunidade.

Esses são os principais pontos que gostaria de analisar, por favor vamos debater nos comentários os conteúdos a serem inseridos em cada nível de estudo.

**Comment by rafa-maciel** [comment]
Perfeito!

**Comment by AndersonMarquess** [comment]
Apoiado! Conforme expliquei no slack, no que eu puder ajudar, pode contar comigo.

**Comment by Diego-Brocanelli** [comment]
Vamos aguardar mais reviews da comunidade e segunda realizamos o merge :)

**Comment by Diego-Brocanelli** [comment]
Bom dia, pessoal.

Podemos realizar o merge da PR https://github.com/training-center/java-study-group/pull/11
