### ISSUE TITLE
O que falta para a galera participar mais?

### ISSUE THREAD

**Issue by vicenthy** [training-center/java-study-group#6]
Queria saber da galera o que ta faltando pra gente deixar o grupo mais agitado? 

Bom, de cara eu pensei: "deve ta geral enrolado e sem tempo" 

Mas tipo eu também to bem enrolado com vários projeto e várias coisas acontecendo ao mesmo tempo, mas to sempre por aqui(github, slack, twitter etc) e então queria saber de vocês, o que ta faltando pra galera participar mais do grupo?

**Comment by woliveiras** [comment]
É algo legal de se perguntar, mano

Normalmente os grupos demoram para engrenar, mas depois que pegam vão embora

**Comment by vicenthy** [comment]
É @woliveiras vamos ver se alguém aparece e da uma dica de como melhorar isso.

**Comment by woliveiras** [comment]
No grupo de PHP está tudo muito movimentado, como tem feito, @Diego-Brocanelli?

**Comment by Diego-Brocanelli** [comment]
Olá, pessoal.

Nós do grupo de estudos de PHP/POO seguimos os seguintes princípios.

- Todos são iguais.
- Todos podem e devem auxiliar no que for possível.
- Falhas ou erros não devem ser omitidos e sim discutidos para resolução do mesmo.
- Sempre reforçamos o compromisso do grupo para com o grupo.
- Sempre reforçamos que o grupo não tem dono, pois todos os integrantes compõem o grupo.
- Caso ocorra de falha de compromisso, reforçamos a importância do comprometimento individual para a manutenção do grupo.
- Temos plena consciência que em alguns momentos alguns membros podem ficar mais distante devido a compromissos, pessoais ou no trabalho.
- Sempre mantermos o foco nas metas definidas em grupo.
- O líder sempre deve estar presente, mesmo que não interagindo diretamente, entretanto para manter a organização e as metas alinhadas.

Bom esses são alguns pontos que me vem em mente agora, um ponto importante é lembrar que quem entrou no grupo é por que tem interesse. E caso não há movimentação no grupo, faça perguntas diretas no Slack, como por exemplo:

- ***O que vocês estão achando do grupo?***
- ***Quais pontos não estão bacanas?***
- ***O que podemos melhorar?***

E lembrar que não é responsabilidade do líder criar estruturas para que sigam o estudos, esse planejamento é coletivo e caso algo não esteja bacana o grupo que deve analisar e mudar!

Espero ter auxiliado, qualquer dúvida podem me acionar.

**Comment by vicenthy** [comment]
Dando uma espiada rápida no repositório do grupo notei que a galera interagi bem com issues, no nosso grupo era mais via Slack e acabei notando que via Slack é um pouco mais difícil de acompanhar os assuntos, então estou criando issues pra ver se melhora pro pessoal.

**Comment by Diego-Brocanelli** [comment]
@vicenthy  Nós sempre incentivamos a levar toda tomada de decisão para ser realizado por meio de issue, pois realmente fica mais fácil e organizado de se fazer.

Sempre após abertura de uma issue, a mesma é divulgada no slack para que o grupo tenha conhecimento da mesma, com isso interagir e inserir suas respectivas opiniões e pontos.

**Comment by vicenthy** [comment]
Legal já está dando pra ver os resultados, vlw mesmo :)

**Comment by Diego-Brocanelli** [comment]
Olá, @vicenthy 

Podemos encerrar essa issue?

**Comment by vicenthy** [comment]
Oxe pensei que tinha encerrado rs
