### ISSUE TITLE
Se apresente

### ISSUE THREAD

**Issue by vicenthy** [training-center/java-study-group#8]
Resolvi criar essa issues pra galera se apresentar e saber  quem realmente tá afim de seguir com o grupo, pois o grupo ficou muito parado.

**Comment by Morette** [comment]
No início eu estava muito empolgado com o grupo, porém tive alguns problemas (ou melhorias) de percurso e hoje preciso dar foco em Python e JS e por isso estou estudando mais a fundo estas linguagens.
:(

**Comment by SilvaAllan** [comment]
Fala galera, Allan aqui . Eu preciso e quero aprender java, mas também dicas do que mais aprender juntamente com java para conseguir meu primeiro emprego na área que no momento meu objetivo. Só não sei muito como fazer, por isso venho acompanhando o grupo mas não postando nada. Mas estou aqui e quero aprender o mais rapido possível

**Comment by rafa-maciel** [comment]
E ae pessoal, também quero aprender a ajudar mais a comunidade, venho estudando a um tempo sozinho e não tenho quase nenhum contato com pessoas da área.

**Comment by taciossbr** [comment]
Eu ja estudo um java sozinho a pouco tempo quero aprender mais, ajudar no que for possível, e principalmente conhecer uma galera da área.

**Comment by osergioneto** [comment]
Olá, me chamo Sérgio Neto.
Estava estudando front-end porém algumas coisas me fizeram mudar (https://thenextweb.com/syndication/2018/02/11/can-train-ai-convert-design-mockups-html-css/) o rumo do que vou estudar.
Como passei a estudar Java na faculdade e precisar desenvolver um app em um projeto, resolvi me dedicar ao estudo de Java.

**Comment by nandumoura** [comment]
Estou aprendendo java agora na faculdade gostaria de uma trilha de estudos a daqui esta vazia

**Comment by Diego-Brocanelli** [comment]
Bom dia, esta issue se mostra relevante, ou podemos encerra-la?

**Comment by vicenthy** [comment]
Pode
